name: Update README with AoC Stars

on:
  push:
    branches:
      - main  # Adjust to your default branch if different
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch AoC Data
        run: |
          curl -s https://adventofcode.com/2024/leaderboard/private/view/2235896.json \
          -H "Cookie: session=${{ secrets.AOC_SESSION }}" \
          > leaderboard.json

      - name: Extract Star Count
        id: get-stars
        run: |
          STARS=$(jq '.members["2235896"].stars' leaderboard.json)
          echo "stars=$STARS" >> $GITHUB_ENV

      - name: Update README
        run: |
          # Update total star count
          sed -i -E "s/\*\*Total Stars Collected\*\*: [0-9]+/\*\*Total Stars Collected\*\*: ${{ env.stars }}/" README.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with latest AoC stars and progress"
